### ISSUE TITLE
Mini Lab 7: GrayScale

### ISSUE THREAD

**Issue by QwikSP** [D1935827V/spring_portfolio#32]
- [x] Make grayscale site work
- [x]  Add grayscale for all imgs
- [ ]  Do a setup with 10 imgs
- [ ] make 2 get mappings into 1 get mapping in ctrl
- [ ] make jpeg work

https://github.com/D1935827V/spring_portfolio/blob/c07075feed65525b3370597de5b263a74d8f9aea/src/main/resources/templates/MiniLab5/MiniLab5.html#L1-L72
https://github.com/D1935827V/spring_portfolio/blob/c07075feed65525b3370597de5b263a74d8f9aea/src/main/resources/templates/MiniLab5/image_grayscale.html#L1-L28
https://github.com/D1935827V/spring_portfolio/blob/c07075feed65525b3370597de5b263a74d8f9aea/src/main/java/com/example/sping_portfolio/controllers/MiniLab5_CTRL.java#L1-L56
https://github.com/D1935827V/spring_portfolio/blob/c07075feed65525b3370597de5b263a74d8f9aea/src/main/java/com/example/sping_portfolio/Image/ImageInfo.java#L1-L322

**Comment by ncrxue** [comment]
[https://github.com/D1935827V/spring_portfolio/issues/21](My issue)
